In [1]:

import pandas as pd

print(pd.__version__)

2.2.2

In [2]:
d = {'hobi':['jogging', 'mancing', 'renang',
             'mancing', 'mancing', 'baca', 
             'baca', 'mancing', 'fotograsi', 
             'mancing', 'camping']}

df = pd.DataFrame(d)
df

         hobi
0     jogging
1     mancing
2      renang
3     mancing
4     mancing
5        baca
6        baca
7     mancing
8   fotograsi
9     mancing
10    camping

In [3]:
df['hobi'].value_counts()

hobi
mancing      5
baca         2
jogging      1
renang       1
fotograsi    1
camping      1
Name: count, dtype: int64

In [4]:

persentase = df['hobi'].value_counts(normalize=True)
persentase

hobi
mancing      0.454545
baca         0.181818
jogging      0.090909
renang       0.090909
fotograsi    0.090909
camping      0.090909
Name: proportion, dtype: float64

In [5]:
threshold = 0.1
hobi_lain = persentase[persentase < threshold].index
hobi_lain

Index(['jogging', 'renang', 'fotograsi', 'camping'], dtype='object', name='hobi')

In [6]:

df['hobi'] = df['hobi'].replace(hobi_lain, 'lainnya')
df['hobi']

0     lainnya
1     mancing
2     lainnya
3     mancing
4     mancing
5        baca
6        baca
7     mancing
8     lainnya
9     mancing
10    lainnya
Name: hobi, dtype: object

In [7]:
df['hobi'].value_counts(normalize=True)

hobi
mancing    0.454545
lainnya    0.363636
baca       0.181818
Name: proportion, dtype: float64

In [8]:
data = {'nama':['bejo', 'tejo', 'wati', 'tiwi', 'cecep'],'jenis_kelamin':['L', 'L', 'P', 'P', 'L'],'umur':[20, 21, 19, 20, 22]}
df = pd.DataFrame(data)

In [9]:
df.to_csv('data_peserta.csv')

In [10]:
df = pd.read_csv('data_peserta.csv')

In [11]:
df.to_csv('data_peserta_tanpa_index.csv', index=False)
df = pd.read_csv('data_peserta_tanpa_index.csv')

In [12]:
import numpy as np

n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), columns=cols)
df

   A  B  C  D  E
0  7  1  4  8  1
1  8  3  8  9  4
2  1  9  3  4  3
3  3  1  9  9  2
4  5  8  8  7  1
5  3  9  5  7  4
6  9  8  9  3  9
7  4  2  7  3  2
8  6  5  1  6  2
9  7  7  7  2  5

In [13]:

df [df['A'] > 5].sum()

A    37
B    24
C    29
D    28
E    21
dtype: int64

In [14]:
df [df['A'] > 5].mean()

A    7.4
B    4.8
C    5.8
D    5.6
E    4.2
dtype: float64

In [15]:
data = {'nama':['bejo', 'tejo', 'wati', 'tiwi', 'cecep'],'jenis_kelamin':['L', 'L', 'P', 'P', 'L'],'umur':[20, 21, 19, 20, 22]}
df = pd.DataFrame(data)
df

    nama jenis_kelamin  umur
0   bejo             L    20
1   tejo             L    21
2   wati             P    19
3   tiwi             P    20
4  cecep             L    22

In [16]:
usia = df.pop('umur').to_frame()

In [17]:

df

    nama jenis_kelamin
0   bejo             L
1   tejo             L
2   wati             P
3   tiwi             P
4  cecep             L

In [18]:

print(usia)

   umur
0    20
1    21
2    19
3    20
4    22